
spring:
  main:
    allow-bean-definition-overriding: true
security:
  oauth2:
    client:
      logout-uri: http://uaa.lhstack.com:9720/oauth2/logout
      client-id: 8426da52ea2e3832e688
      client-secret: c52bed46f4c40d52f2154eeb0eea905c8cba4468
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      use-current-uri: true #如果为false，则重定向url使用pre-established-redirect-uri
      pre-established-redirect-uri: http://localhost:8080/oauth/token_receive
      token-name: access_token
    resource:
      user-info-uri:  https://api.github.com/user
    sso:
      login-path: /login/oauth2/code/sso #配置重定向页面
server:
  port: 8080
debug: true